"""migration test

Revision ID: 66a5a55cc444
Revises: fd0cb065b081
Create Date: 2026-04-21 14:04:18.387077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a5a55cc444'
down_revision = 'fd0cb065b081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idade', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'teams', ['team_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('team_id')
        batch_op.drop_column('idade')

    # ### end Alembic commands ###
