"""Adding JWT

Revision ID: 851aa8ec77e0
Revises: fd0cb065b081
Create Date: 2026-07-06 09:55:06.855171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '851aa8ec77e0'
down_revision = 'fd0cb065b081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha_hash', sa.String(length=255), nullable=False))
        batch_op.drop_column('senha')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('senha_hash')

    # ### end Alembic commands ###
