"""empty message

Revision ID: f5a795c9c868
Revises: 9896a8b154f3
Create Date: 2026-04-21 14:10:03.066511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5a795c9c868'
down_revision = '9896a8b154f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_teams_name'), ['name'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idade', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.create_foreign_key(batch_op.f('fk_users_team_id_teams'), 'teams', ['team_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_team_id_teams'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        batch_op.drop_column('team_id')
        batch_op.drop_column('idade')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_teams_name'), type_='unique')

    # ### end Alembic commands ###
